// npm install --prefix tests/.pcr-tools playwright@1.63.0
// PLAYWRIGHT_BROWSERS_PATH=tests/.pcr-tools/browsers node tests/pcr-browser.mjs
import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { exerciseIntro } from './pcr-intro-browser.mjs';
import { emptyRecord, STORAGE_KEY } from '../assets/js/pcr-records.mjs';
import { chromium, webkit } from './.pcr-tools/node_modules/playwright/index.mjs';
const url = process.env.PCR_TEST_URL || 'http://127.0.0.1:4173/bioinformatics/pcr-primer-design/';
const output = resolve('tests/.pcr-output'); await mkdir(output, { recursive: true });
let checks = 0;
const check = (value, label) => { assert.ok(value, label); checks++; };
const P1 = ['AGTCGATGCTACGTTGACCA', 'TTCAGGCTACGATCGTACGA'];
for (const [name, engine] of Object.entries({ chromium, webkit })) {
  const browser = await engine.launch({ headless: true });
  for (const width of [1440, 768, 390]) {
    const context = await browser.newContext({ viewport: { width, height: 1000 }, hasTouch: width === 390 });
    const page = await context.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto(url); await page.waitForSelector('#pcr-worksheet[data-ready=true]');
    check(await page.locator('#analysis-results').innerText().then(t => !t.includes('260')), `${name} initial answer hidden`);
    check(await page.locator('#worksheet-toc').evaluate(e => e.open) === (width > 900), 'responsive table of contents');
    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${name}/${width} no horizontal overflow`);
    check(!/[\u00b7\u2022\u2027\u2219\u22c5\u30fb\u318d]/u.test(await page.locator('body').innerText()), 'no displayed forbidden dots');
    check(await page.locator('input:not([type=file]),textarea,select').evaluateAll(elements => elements.every(e => e.labels.length)), 'all fields have labels');
    await page.screenshot({ path: resolve(output, `${name}-${width}-opening.png`) });
    await page.locator('#first-placement').fill('처음 예측: 결실 양옆을 확인한다.');
    await exerciseIntro(page, width, name, check, output);
    await page.locator('#coordinate-details > summary').click();
    await page.locator('#range-start').fill('41'); await page.locator('#range-end').fill('60'); await page.locator('#apply-range').click();
    check(await page.locator('#primer-f').inputValue() === P1[0], 'numeric forward range');
    await page.locator('#range-primer').selectOption('R'); await page.locator('#range-direction').selectOption('left');
    await page.locator('#range-start').fill('281'); await page.locator('#range-end').fill('300'); await page.locator('#apply-range').click();
    check(await page.locator('#primer-r').inputValue() === P1[1], 'numeric reverse range');
    await page.locator('[data-select-primer=F]').click();
    check(await page.locator('.pcr-base').count() === (width === 390 ? 30 : 60), 'bounded sequence window');
    const cell1 = page.locator('[data-base="41"]'), cell2 = page.locator('[data-base="60"]');
    if (width === 390) { await cell1.tap(); await cell2.tap(); }
    else { await cell1.click(); await cell2.click(); }
    check(await page.locator('#range-start').inputValue() === '41' && await page.locator('#range-end').inputValue() === '60', 'pointer/touch endpoints');
    await cell1.focus(); await page.keyboard.press('Enter'); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Enter');
    check(await page.locator('#range-end').inputValue() === '42', 'keyboard selection');
    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'sequence no overflow');
    await page.locator('#sequence-details').scrollIntoViewIfNeeded(); await page.screenshot({ path: resolve(output, `${name}-${width}-sequence.png`) });
    await page.locator('#range-start').fill('41'); await page.locator('#range-end').fill('60'); await page.locator('#apply-range').click();
    await page.locator('#design-reflection > summary').click();
    await page.locator('#manual-sequences > summary').click();
    await page.locator('#design-prediction').fill('AとBでは長さが異なると予想する。');
    await page.locator('#design-reason').fill('결실 양옆에 배치했다.'); await page.locator('#design-unresolved').fill('실제 유전체 특이성');
    await page.locator('#analyze-design').click();
    await page.locator('#analysis-results summary').click();
    check((await page.locator('#analysis-results').innerText()).includes('A 41~300: 260 bp'), 'P1 A');
    check((await page.locator('#analysis-results').innerText()).includes('B 41~220: 180 bp'), 'P1 B');
    check((await page.locator('#gel-results').innerText()).includes('A+C'), 'mixture gel');
    await page.locator('#save-design').click();
    await page.locator('#primer-f').fill('ACNT'); await page.locator('#analyze-design').click();
    check((await page.locator('#analysis-status').innerText()).includes('3번 N'), 'invalid base position');
    check((await page.locator('#saved-designs').innerText()).includes(P1[0]), 'snapshot unchanged');
    check(!(await page.locator('#gel-results').innerText()).includes('260'), 'stale results cleared');
    await page.locator('#compare-ab').click(); check(!(await page.locator('#candidate-results').innerText()).includes('220 bp'), 'AB comparison');
    await page.locator('#compare-abc').click(); check((await page.locator('#candidate-results').innerText()).includes('C 101~320: 220 bp'), 'ABC comparison');
    await page.getByRole('button', { name: 'P2을 편집 입력으로 가져오기', exact: true }).click();
    await page.locator('#save-design').click();
    await page.getByRole('button', { name: 'P3을 편집 입력으로 가져오기', exact: true }).click();
    await page.locator('#save-design').click(); check(await page.locator('#save-design').isDisabled(), 'three preserved designs');
    await page.locator('#external-mode').selectOption({ label: '새 후보 설계' });
    await page.locator('#external-plan').fill('미실시: 교사가 지정한 RefSeq와 검색 범위를 확인한다.');
    const longAnswer = '긴 답안의 모든 문장이 출력되어야 한다.\n'.repeat(100) + '마지막 확인 문장';
    await page.locator('#final-evidence').fill(longAnswer);
    await page.locator('#final-revision').fill('<img src=x onerror="window.pcrInjected=true">도 텍스트로 남긴다.');
    await page.reload(); await page.waitForSelector('#pcr-worksheet[data-ready=true]');
    check(await page.locator('#first-placement').inputValue() === '처음 예측: 결실 양옆을 확인한다.', 'reload answers');
    check(await page.locator('#saved-designs .pcr-saved').count() === 3, 'reload snapshots');
    const downloadPromise = page.waitForEvent('download'); await page.locator('#record-menu > summary').click(); await page.locator('#export-record').click(); const download = await downloadPromise;
    const filename = resolve(output, `${name}-${width}-roundtrip.json`); await download.saveAs(filename);
    const exported = JSON.parse(await readFile(filename, 'utf8'));
    check(exported.initialPrimerPrediction.forward !== null && exported.initialPrimerPrediction.reverse !== null, 'initial prediction exported');
    check(exported.answers['cycle-boundary-choice'] === 'primer-pair' && exported.answers['direction-end-choice'] === '3', 'choices exported');
    check(exported.schemaVersion === 1 && exported.dataVersion && exported.updatedAt, 'versioned export');
    await page.locator('#first-placement').fill('임시 수정');
    await page.locator('#record-menu > summary').click();
    page.once('dialog', d => d.accept()); await page.locator('#import-record').setInputFiles(filename);
    await page.waitForFunction(() => document.querySelector('#first-placement').value.startsWith('처음 예측'));
    check(await page.locator('#final-evidence').inputValue() === longAnswer, 'JSON round trip preserves long answers');
    check(await page.locator('#prediction-forward').inputValue() === String(exported.initialPrimerPrediction.forward), 'initial prediction imported');
    check(!await page.evaluate(() => window.pcrInjected), 'import remains inert text');
    await page.locator('#import-record').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"schemaVersion":2}') });
    await page.waitForFunction(() => document.querySelector('#save-status').textContent.includes('불러오기 실패'));
    check((await page.locator('#save-status').innerText()).includes('불러오기 실패'), 'invalid import rejected');
    await page.evaluate(() => { window.print = () => window.dispatchEvent(new Event('beforeprint')); });
    await page.locator('#print-menu > summary').click(); await page.locator('#print-filled').click(); await page.emulateMedia({ media: 'print' });
    check((await page.locator('#final-evidence + .pcr-print-value').innerText()).endsWith('마지막 확인 문장'), 'full print answer');
    check(await page.locator('.pcr-explanation').first().isHidden(), 'print explanations excluded');
    check(await page.locator('#prediction-forward-marker').isVisible(), 'filled print retains initial markers');
    check((await page.locator('[data-choice=cycle-boundary-choice] .pcr-print-value').innerText()) === 'primer pair', 'filled print includes selected choice');
    if (name === 'chromium' && width === 1440) await page.pdf({ path: resolve(output, 'filled-notebook.pdf'), format: 'A4', printBackground: true });
    await page.emulateMedia({ media: 'screen' }); await page.evaluate(() => window.dispatchEvent(new Event('afterprint')));
    await page.locator('#print-blank').click(); await page.emulateMedia({ media: 'print' });
    check(await page.locator('#final-evidence + .pcr-print-value').innerText() === '', 'blank print empty');
    check(await page.locator('#saved-designs').isHidden(), 'blank print saved answers excluded');
    check(await page.locator('#prediction-forward-marker').isHidden() && await page.locator('#prediction-reverse-marker').isHidden(), 'blank print excludes initial markers');
    check(await page.locator('#reverse-demonstration').isHidden() && await page.locator('.pcr-confirmed-complement').isHidden(), 'blank print excludes revealed sequence answers');
    check((await page.locator('[data-choice=cycle-boundary-choice] .pcr-print-value').innerText()) === '', 'blank print excludes selected choice');
    if (name === 'chromium' && width === 1440) await page.pdf({ path: resolve(output, 'blank-worksheet.pdf'), format: 'A4', printBackground: true });
    await page.emulateMedia({ media: 'screen' }); await page.evaluate(() => window.dispatchEvent(new Event('afterprint')));
    check(await page.locator('#final-evidence').inputValue() === longAnswer, 'blank print keeps record');
    await page.evaluate(() => localStorage.setItem('unrelated-test', 'keep'));
    await page.locator('#record-menu > summary').click();
    page.once('dialog', d => d.dismiss()); await page.locator('#reset-record').click();
    check(await page.locator('#saved-designs .pcr-saved').count() === 3, 'reset cancellation');
    page.once('dialog', d => d.accept()); await page.locator('#reset-record').click();
    check(await page.locator('#first-placement').inputValue() === '', 'reset this worksheet');
    check(await page.locator('#prediction-forward-marker').isHidden() && await page.locator('#reverse-step').isHidden(), 'reset clears new introductory activity state');
    check(await page.evaluate(() => localStorage.getItem('unrelated-test')) === 'keep', 'other storage preserved');
    check(errors.length === 0, `no runtime errors: ${errors.join(', ')}`);
    console.log(`PASS ${name} ${width}px`); await context.close();
  }
  const legacy = emptyRecord(); delete legacy.initialPrimerPrediction; delete legacy.introView;
  legacy.cycle = 2;
  legacy.answers = { 'first-placement': '이전 위치 예측', 'first-negative': '이전 대조군 기록', 'direction-complement': 'TCAGGCAT', 'direction-reverse': 'TACGGACT' };
  legacy.draft = { forward: P1[0], reverse: P1[1] };
  legacy.designs = [{ id: 1, createdAt: legacy.updatedAt, forward: P1[0], reverse: P1[1], prediction: '이전 설계 예상', reason: '이전 근거', unresolved: '특이성 미확인' }];
  const oldContext = await browser.newContext();
  await oldContext.addInitScript(({ key, record }) => { if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify(record)); }, { key: STORAGE_KEY, record: legacy });
  const oldPage = await oldContext.newPage(); await oldPage.goto(url); await oldPage.waitForSelector('#pcr-worksheet[data-ready=true]');
  check(await oldPage.locator('#first-placement').inputValue() === '이전 위치 예측', 'legacy local record restored');
  check(await oldPage.locator('[data-cycle-stage=extension]').getAttribute('aria-pressed') === 'true', 'legacy three-step position migrated');
  await oldPage.locator('#legacy-first-negative > summary').click();
  check(await oldPage.locator('#first-negative').inputValue() === '이전 대조군 기록', 'legacy removed prompt remains accessible');
  check(await oldPage.locator('#saved-designs .pcr-saved').count() === 1, 'legacy design preserved');
  await oldPage.locator('#record-menu > summary').click();
  oldPage.once('dialog', dialog => dialog.accept());
  await oldPage.locator('#import-record').setInputFiles({ name: 'legacy.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(legacy)) });
  await oldPage.waitForFunction(() => document.querySelector('#save-status').textContent.includes('자동 저장했습니다'));
  check(await oldPage.locator('#primer-r').inputValue() === P1[1], 'legacy JSON import keeps draft');
  await oldPage.locator('#manual-sequences > summary').click();
  await oldPage.locator('#analyze-design').click();
  check((await oldPage.locator('#analysis-results').innerText()).includes('260 bp'), 'legacy imported design calculates');
  await oldContext.close();
  const blocked = await browser.newContext(); await blocked.addInitScript(() => Object.defineProperty(window, 'localStorage', { get() { throw new Error('Storage blocked'); } }));
  const page = await blocked.newPage(); await page.goto(url); await page.waitForSelector('#pcr-worksheet[data-ready=true]');
  await page.locator('#first-placement').fill('저장 차단 상태 기록'); check((await page.locator('#save-status').innerText()).includes('읽을 수 없습니다'), 'blocked storage notice');
  const d = page.waitForEvent('download'); await page.locator('#record-menu > summary').click(); await page.locator('#export-record').click(); await d; checks++; await blocked.close();
  const nojs = await browser.newContext({ javaScriptEnabled: false }); const staticPage = await nojs.newPage(); await staticPage.goto(url);
  check(await staticPage.locator('#activity-07').innerText().then(t => t.includes('최종 설계 기록')), 'no-JS readable activities');
  check(await staticPage.locator('noscript').innerText().then(t => t.includes('종이에')), 'no-JS instructions'); await nojs.close();
  await browser.close();
}
console.log(`PASS ${checks} browser assertions`);
