name: Build & Deploy Jekyll

on:
  push:
    branches: [ main ]   # 원본 작업 브랜치

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-ruby@v1
        with: { ruby-version: '3.2' }
      - run:  gem install bundler && bundle install
      - run:  JEKYLL_ENV=production bundle exec jekyll build -d _site
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages   # 배포용 분리 브랜치
