name: Build & Deploy Jekyll

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false        # 캐시 대신 우리가 직접 install

      - run: bundle install --jobs 4 --retry 3   # ←★ Gem 설치 단계
      - run: bundle exec jekyll build -d _site   # ←★ 이제 Jekyll 실행 가능

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
